"""add gate-related denial reason enums

Revision ID: d55bb1354961
Revises: d16c6bebecd1
Create Date: 2026-04-23 10:36:57.186813

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '09f228d1f329'
down_revision: Union[str, Sequence[str], None] = 'd55bb1354961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_denial_reason_consistency",
        "your_table_name",
        type_="check"
    )
    
    op.create_check_constraint(
        "check_denial_reason_consistency",
        "your_table_name",
        "(result = 'GRANTED') = (denial_reason IS NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_denial_reason_consistency",
        "your_table_name",
        type_="check"
    )
    
    op.create_check_constraint(
        "check_denial_reason_consistency",
        "your_table_name",
        "(result = 'DENIED') = (denial_reason IS NOT NULL)"
    )
    # ### end Alembic commands ###
