"""make_venue_name_unique

Revision ID: 11218c12741d
Revises: d2e3f4g5h6i7
Create Date: 2026-04-28 14:09:16.230757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11218c12741d'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4g5h6i7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_attempt_log', 'gate_id_raw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scan_attempt_log', 'error_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_venue_name'), table_name='venue')
    op.create_index('ix_venue_name', 'venue', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_venue_name', table_name='venue')
    op.create_index(op.f('ix_venue_name'), 'venue', ['name'], unique=False)
    op.alter_column('scan_attempt_log', 'error_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_attempt_log', 'gate_id_raw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
