"""nullable_log_event_id_add_uin_hash_rename_result_enum

Revision ID: 529057d8a053
Revises: e3acf559c6fd
Create Date: 2026-04-21 17:24:35.205964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529057d8a053'
down_revision: Union[str, Sequence[str], None] = 'e3acf559c6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('uin_hash', sa.String(), nullable=True))
    op.alter_column('log', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("ALTER TYPE log_result RENAME VALUE 'granted' TO 'grant'")
    op.execute("ALTER TYPE log_result RENAME VALUE 'denied' TO 'deny'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE log_result RENAME VALUE 'grant' TO 'granted'")
    op.execute("ALTER TYPE log_result RENAME VALUE 'deny' TO 'denied'")
    op.alter_column('log', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('log', 'uin_hash')
    # ### end Alembic commands ###
