"""test hello?

Revision ID: 52f9f6453b6b
Revises: 
Create Date: 2026-04-30 15:47:01.123017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f9f6453b6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_index('ix_venue_name', 'venue', ['name'], unique=False)
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'CONCLUDED', 'CANCELLED', name='event_status'), server_default='SCHEDULED', nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_if_event_time_valid'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_event_status', 'event', ['status'], unique=False)
    op.create_index('ix_event_time_range', 'event', ['start_time', 'end_time'], unique=False)
    op.create_index('ix_event_venue_id', 'event', ['venue_id'], unique=False)
    op.create_table('gate',
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='gate_status'), server_default='OFFLINE', nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('gate_id')
    )
    op.create_index('ix_gate_status', 'gate', ['status'], unique=False)
    op.create_index('ix_gate_venue_id', 'gate', ['venue_id'], unique=False)
    op.create_table('event_ticket_link',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('link_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('link_hash')
    )
    op.create_index('ix_link_event_id', 'event_ticket_link', ['event_id'], unique=False)
    op.create_index('ix_link_hash', 'event_ticket_link', ['link_hash'], unique=False)
    op.create_table('gate_assignment',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='assignment_status'), server_default='ACTIVE', nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'INACTIVE'::assignment_status) = (unassigned_at IS NOT NULL)", name='check_unassigned_at_consistency'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['gate.gate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index('ix_gate_assignment_event_id', 'gate_assignment', ['event_id'], unique=False)
    op.create_index('ix_gate_assignment_gate_id', 'gate_assignment', ['gate_id'], unique=False)
    op.create_index('ix_gate_assignment_status', 'gate_assignment', ['status'], unique=False)
    op.create_index('uq_gate_assignment_active_gate', 'gate_assignment', ['gate_id'], unique=True, postgresql_where="status = 'ACTIVE'")
    op.create_table('ticket',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNUSED', 'USED', name='ticket_status'), server_default='UNUSED', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Manila', now())"), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'USED'::ticket_status) = (used_at IS NOT NULL)", name='check_used_at_consistency'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['event_ticket_link.link_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('link_id')
    )
    op.create_index('ix_ticket_event_id', 'ticket', ['event_id'], unique=False)
    op.create_index('ix_ticket_link_id', 'ticket', ['link_id'], unique=False)
    op.create_index('ix_ticket_status', 'ticket', ['status'], unique=False)
    op.create_index('ix_ticket_used_at', 'ticket', ['used_at'], unique=False)
    op.create_table('log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', 'TIMEOUT', 'ERROR', name='log_result'), nullable=False),
    sa.Column('denial_reason', sa.Enum('INVALID_GATE_ID', 'GATE_OFFLINE', 'INVALID_GATE_ASSIGNMENT', 'EVENT_NOT_FOUND', 'EVENT_CONCLUDED', 'EVENT_CANCELLED', 'IDENTITY_NOT_VERIFIED', 'LINK_NOT_FOUND', 'WRONG_EVENT', 'TICKET_NOT_FOUND', 'TICKET_ALREADY_USED', 'SERVER_TIMEOUT', 'INTERNAL_SERVER_ERROR', name='denial_reason'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text("timezone('Asia/Manila', now())"), nullable=False),
    sa.Column('event_name_snapshot', sa.String(), nullable=True),
    sa.Column('raw_gate_id_snapshot', sa.String(), nullable=False),
    sa.Column('gate_location_snapshot', sa.String(), nullable=True),
    sa.Column('ticket_status_snapshot', sa.String(), nullable=True),
    sa.CheckConstraint("(result = 'GRANTED') = (denial_reason IS NULL)", name='check_denial_reason_consistency'),
    sa.CheckConstraint("result NOT IN ('TIMEOUT', 'ERROR') OR ticket_id IS NULL", name='check_ticket_absent_on_system_failure'),
    sa.CheckConstraint('(event_id IS NULL) = (event_name_snapshot IS NULL)', name='check_event_snapshot_consistency'),
    sa.CheckConstraint('(gate_id IS NULL) = (gate_location_snapshot IS NULL)', name='check_gate_snapshot_consistency'),
    sa.CheckConstraint('(ticket_id IS NULL) = (ticket_status_snapshot IS NULL)', name='check_ticket_snapshot_consistency'),
    sa.ForeignKeyConstraint(['assignment_id'], ['gate_assignment.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gate.gate_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_log_assignment_id', 'log', ['assignment_id'], unique=False)
    op.create_index('ix_log_event_gate_time', 'log', ['event_id', 'gate_id', 'timestamp'], unique=False)
    op.create_index('ix_log_event_id', 'log', ['event_id'], unique=False)
    op.create_index('ix_log_gate_id', 'log', ['gate_id'], unique=False)
    op.create_index('ix_log_ticket_id', 'log', ['ticket_id'], unique=False)
    op.create_index('ix_log_timestamp', 'log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_timestamp', table_name='log')
    op.drop_index('ix_log_ticket_id', table_name='log')
    op.drop_index('ix_log_gate_id', table_name='log')
    op.drop_index('ix_log_event_id', table_name='log')
    op.drop_index('ix_log_event_gate_time', table_name='log')
    op.drop_index('ix_log_assignment_id', table_name='log')
    op.drop_table('log')
    op.drop_index('ix_ticket_used_at', table_name='ticket')
    op.drop_index('ix_ticket_status', table_name='ticket')
    op.drop_index('ix_ticket_link_id', table_name='ticket')
    op.drop_index('ix_ticket_event_id', table_name='ticket')
    op.drop_table('ticket')
    op.drop_index('uq_gate_assignment_active_gate', table_name='gate_assignment', postgresql_where="status = 'ACTIVE'")
    op.drop_index('ix_gate_assignment_status', table_name='gate_assignment')
    op.drop_index('ix_gate_assignment_gate_id', table_name='gate_assignment')
    op.drop_index('ix_gate_assignment_event_id', table_name='gate_assignment')
    op.drop_table('gate_assignment')
    op.drop_index('ix_link_hash', table_name='event_ticket_link')
    op.drop_index('ix_link_event_id', table_name='event_ticket_link')
    op.drop_table('event_ticket_link')
    op.drop_index('ix_gate_venue_id', table_name='gate')
    op.drop_index('ix_gate_status', table_name='gate')
    op.drop_table('gate')
    op.drop_index('ix_event_venue_id', table_name='event')
    op.drop_index('ix_event_time_range', table_name='event')
    op.drop_index('ix_event_status', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_venue_name', table_name='venue')
    op.drop_table('venue')
    # ### end Alembic commands ###
