"""initial_schema

Revision ID: 72f43e6883e2
Revises: 
Create Date: 2026-04-21 15:59:07.771375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f43e6883e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop stale enum types left behind by the old Supabase SQL migrations
    op.execute("DROP TYPE IF EXISTS ticket_tier CASCADE")
    op.execute("DROP TYPE IF EXISTS ticket_status CASCADE")
    op.execute("DROP TYPE IF EXISTS scan_result CASCADE")
    op.execute("DROP TYPE IF EXISTS denial_reason CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_index('ix_venue_name', 'venue', ['name'], unique=False)
    op.create_table('event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_if_event_time_valid'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_event_time_range', 'event', ['start_time', 'end_time'], unique=False)
    op.create_index('ix_event_venue_id', 'event', ['venue_id'], unique=False)
    op.create_table('event_ticket_link',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('link_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('link_hash')
    )
    op.create_index('ix_link_event_id', 'event_ticket_link', ['event_id'], unique=False)
    op.create_index('ix_link_hash', 'event_ticket_link', ['link_hash'], unique=False)
    op.create_table('gate',
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='gate_status'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.venue_id'], ),
    sa.PrimaryKeyConstraint('gate_id')
    )
    op.create_index('ix_gate_event_id', 'gate', ['event_id'], unique=False)
    op.create_index('ix_gate_status', 'gate', ['status'], unique=False)
    op.create_index('ix_gate_venue_id', 'gate', ['venue_id'], unique=False)
    op.create_table('ticket',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNUSED', 'USED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['event_ticket_link.link_id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('link_id')
    )
    op.create_index('ix_ticket_link_id', 'ticket', ['link_id'], unique=False)
    op.create_index('ix_ticket_status', 'ticket', ['status'], unique=False)
    op.create_index('ix_ticket_used_at', 'ticket', ['used_at'], unique=False)
    op.create_table('log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', 'TIMEOUT', 'ERROR', name='log_result'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['gate.gate_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_log_event_gate_time', 'log', ['event_id', 'gate_id', 'timestamp'], unique=False)
    op.create_index('ix_log_event_id', 'log', ['event_id'], unique=False)
    op.create_index('ix_log_gate_id', 'log', ['gate_id'], unique=False)
    op.create_index('ix_log_ticket_id', 'log', ['ticket_id'], unique=False)
    op.create_index('ix_log_timestamp', 'log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_timestamp', table_name='log')
    op.drop_index('ix_log_ticket_id', table_name='log')
    op.drop_index('ix_log_gate_id', table_name='log')
    op.drop_index('ix_log_event_id', table_name='log')
    op.drop_index('ix_log_event_gate_time', table_name='log')
    op.drop_table('log')
    op.drop_index('ix_ticket_used_at', table_name='ticket')
    op.drop_index('ix_ticket_status', table_name='ticket')
    op.drop_index('ix_ticket_link_id', table_name='ticket')
    op.drop_table('ticket')
    op.drop_index('ix_gate_venue_id', table_name='gate')
    op.drop_index('ix_gate_status', table_name='gate')
    op.drop_index('ix_gate_event_id', table_name='gate')
    op.drop_table('gate')
    op.drop_index('ix_link_hash', table_name='event_ticket_link')
    op.drop_index('ix_link_event_id', table_name='event_ticket_link')
    op.drop_table('event_ticket_link')
    op.drop_index('ix_event_venue_id', table_name='event')
    op.drop_index('ix_event_time_range', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_venue_name', table_name='venue')
    op.drop_table('venue')
    op.execute("DROP TYPE IF EXISTS gate_status")
    op.execute("DROP TYPE IF EXISTS ticket_status")
    op.execute("DROP TYPE IF EXISTS log_result")
    # ### end Alembic commands ###
