"""add gate-related denial reason enums

Revision ID: d55bb1354961
Revises: d16c6bebecd1
Create Date: 2026-04-23 10:36:57.186813

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'd55bb1354961'
down_revision: Union[str, Sequence[str], None] = 'd16c6bebecd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
