"""add_capacity_and_nullable_gate_venue

Revision ID: e3acf559c6fd
Revises: 72f43e6883e2
Create Date: 2026-04-21 16:27:27.837797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3acf559c6fd'
down_revision: Union[str, Sequence[str], None] = '72f43e6883e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('capacity', sa.Integer(), nullable=False))
    op.alter_column('gate', 'venue_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gate', 'venue_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('event', 'capacity')
    # ### end Alembic commands ###
